### PR TITLE
enabeling bayesian tuner

### PR DESCRIPTION
**Pull request by goergen95**
Hi Turgut,
I guess I am missing the obvious but with the changes in the PR bayesian optimization is enabled as a tuner and not an oracle. Locally it seems to be working fine. 
Am I missing something here or is this the way to go to use standard bayesian optimization provided by keras tuner?
Cheers,
Darius.

### CODE REVIEW

**Comment by goergen95** [comment]
Well, obviously not working yet :) I am going to open an issue for this.

**Comment by henry090** [comment]
@goergen95 You forgot to document. From RStudio try to document all the changes and push docs update as well.

**Comment by goergen95** [comment]
Thanks for pointing this out to me! I implemented your suggestions from #34 to keep both available, the oracle and the tuner. Additionally I tried to add a test for both ways, however it seems to be failing again. I am going to look into it during the next days but if you see something before me please let me know.

**Comment by henry090** [comment]
A minor change to see if it works.

**Comment by henry090** [comment]
They released the second version of ```keras-tuner```. This could be the reason for failure. https://pypi.org/project/keras-tuner/
Could you change the YAML files in  ```.github``` folder to the version of kerastuner (1.0.2) for each OS, please?

**Comment by henry090** [comment]
It probably will fail. Because I see that version is 1.0.1 in ```kerastuneR::install_kerastuner```

```
function(version = NULL, ..., restart_session = TRUE, from_git = FALSE) {
  
  if (is.null(version) & !from_git) {
    module_string <- paste0("keras-tuner==", '1.0.1')
  } else if (!is.null(version)) {
    module_string <- paste0("keras-tuner==", version)
  } else if (isTRUE(from_git)) {
    module_string <- paste0("git+https://github.com/keras-team/keras-tuner.git")
  }
  
  invisible(py_config())
  py_path = Sys.which('python') %>% as.character()
  py_install(packages = paste(module_string, 'pydot'), pip = TRUE, ...)
  
  invisible(use_python(py_path, required = TRUE))
  py_install('pydot')
  
  fun <- function() {
    py_path = gsub(py_path, replacement = '/',pattern = '\\', fixed=TRUE)
    error <- red $ bold
    error2 <- black $ bold
    cat(error2("Keras Tuner is installed here:"), paste('"',error(py_path),'"',sep = ''))
  }
  
  fun()
  
  if (restart_session && rstudioapi::hasFun("restartSession"))
    rstudioapi::restartSession()

}
<bytecode: 0x55dfb3abbce0>
<environment: namespace:kerastuneR>
```
So this could help:

https://github.com/goergen95/kerastuneR/blob/ac43178d92b87939cd81251dabb4dbfedf14d8d3/.github/workflows/keras_tuner_stable.yml#L64

```
Rscript -e "kerastuneR::install_kerastuner(version=Sys.getenv('KERAS_TUNER_VERSION'))"
```

**Comment by goergen95** [comment]
ok I now see these two error messages both on windows and macOS:

```
Message: AttributeError: module 'tensorflow._api.v2.distribute' has no attribute 'TPUStrategy'
```
and 
```
Message: RuntimeError: Evaluation error: ValueError: Unknown metric: loss
```
while running the test for Baysian Optimization as oracle (the test I haven't touched) with TF 2.2.0 and 2.3.0 versus KT 1.0.2

Do you have any suggetions?

**Comment by henry090** [comment]
@goergen95 Yes, it fails on my local Mac, as well. What is ur OS? Does this work for you?

**Comment by henry090** [comment]
From python side this works fine on my Mac. The problem is from R side I guess:

```
turgutabdullayev@Turguts-MacBook-Pro Downloads % /Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/bin/python py_check.py
2020-11-22 23:01:20.105491: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-22 23:01:20.119186: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc77f086640 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-22 23:01:20.119207: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

Search: Running Trial #1

Hyperparameter    |Value             |Best Value So Far 
conv_layers       |1                 |?                 
filters_0         |28                |?                 
kernel_size_0     |4                 |?                 
pooling0          |max               |?                 
filters_1         |16                |?                 
kernel_size_1     |4                 |?                 
pooling1          |avg               |?                 
filters_2         |4                 |?                 
kernel_size_2     |4                 |?                 
pooling2          |avg               |?                 
global_pooling    |max               |?                 
optimizer         |sgd               |?                 
batch_size        |64                |?                 
learning_rate     |0.001             |?                 

Epoch: 0
Batch: 0, Average Loss: 2.4709954261779785
Batch: 100, Average Loss: 2.2906203269958496
Batch: 200, Average Loss: 2.2623729705810547
Batch: 300, Average Loss: 2.22991681098938
Batch: 400, Average Loss: 2.1900992393493652
Batch: 500, Average Loss: 2.142864227294922
Batch: 600, Average Loss: 2.092534303665161
Batch: 700, Average Loss: 2.0369279384613037
Batch: 800, Average Loss: 1.977268099784851
Batch: 900, Average Loss: 1.9162358045578003

Trial 1 Complete [00h 00m 25s]
loss: 1.8232492804527283

Best loss So Far: 1.8232492804527283
Total elapsed time: 00h 00m 25s
{'conv_layers': 1, 'filters_0': 28, 'kernel_size_0': 4, 'pooling0': 'max', 'filters_1': 16, 'kernel_size_1': 4, 'pooling1': 'avg', 'filters_2': 4, 'kernel_size_2': 4, 'pooling2': 'avg', 'global_pooling': 'max', 'optimizer': 'sgd', 'batch_size': 64, 'learning_rate': 0.001}
turgutabdullayev@Turguts-MacBook-Pro Downloads % 
```

**Comment by goergen95** [comment]
Sorry for the long delay. 
I am working on Linux Mint 20, TF 2.3.0, keras 2.4.3.
Currently I am getting this error for the bayesian as oracle test which has not occured before.
```bash
WARNING: Logging before flag parsing goes to stderr.
  W1218 12:34:20.912902 139894345775040 util.py:150] Unresolved object in checkpoint: (root).optimizer.iter
  W1218 12:34:20.913071 139894345775040 util.py:150] Unresolved object in checkpoint: (root).optimizer.beta_1
  W1218 12:34:20.913119 139894345775040 util.py:150] Unresolved object in checkpoint: (root).optimizer.beta_2
  W1218 12:34:20.913159 139894345775040 util.py:150] Unresolved object in checkpoint: (root).optimizer.decay
  W1218 12:34:20.913196 139894345775040 util.py:150] Unresolved object in checkpoint: (root).optimizer.learning_rate
  W1218 12:34:20.913232 139894345775040 util.py:158] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
```

**Comment by henry090** [comment]
@goergen95 On the main page of kerastuneR all the tests passed on October 4. This means that something was changed and that is the reason for the issue with Bayesian Optimization. Can you see the difference after that period? Because it worked with bot TF 2.2 and 2.3 + nightly.

**Pull request closed without merging**
